### ISSUE TITLE
getter methods are undefined

### ISSUE THREAD

**Issue by Datta-192** [sanajitjana/E-Commerce-API#1]
some of the getter methods are undefined
![image](https://github.com/sanajitjana/E-Commerce-API/assets/75350718/f81676e4-c45e-413f-af7d-c6c45b90b4e7)

**Comment by sanajitjana** [comment]
Hi @Datta-192 
To resolve this issue, please make sure that your IDE is using Lombok plugin correctly
Refer this steps https://projectlombok.org/setup/intellij
